// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX_Ue1nbKK5-jPEx3pHWaz7tp83Y5tUWo',
    appId: '1:76985100462:web:5cfaad031aa91ed308e53f',
    messagingSenderId: '76985100462',
    projectId: 'calai-29fd7',
    authDomain: 'calai-29fd7.firebaseapp.com',
    storageBucket: 'calai-29fd7.firebasestorage.app',
    measurementId: 'G-XFDLE05K40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDRnZ-YdBCE12HRKzE-JGQW1UVw0WVOCw',
    appId: '1:76985100462:android:d7117e3dc83a1bcf08e53f',
    messagingSenderId: '76985100462',
    projectId: 'calai-29fd7',
    storageBucket: 'calai-29fd7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASqeDvyG0Ec6XwotQ-ng4Q-3rVyZQ1OoI',
    appId: '1:76985100462:ios:b39a198fe321ffa808e53f',
    messagingSenderId: '76985100462',
    projectId: 'calai-29fd7',
    storageBucket: 'calai-29fd7.firebasestorage.app',
    iosBundleId: 'com.example.calai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASqeDvyG0Ec6XwotQ-ng4Q-3rVyZQ1OoI',
    appId: '1:76985100462:ios:b39a198fe321ffa808e53f',
    messagingSenderId: '76985100462',
    projectId: 'calai-29fd7',
    storageBucket: 'calai-29fd7.firebasestorage.app',
    iosBundleId: 'com.example.calai',
  );
}
